name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run prod

      - name: Publish
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Hany Elemary
          author_email: hany.elemary@gmail.com
          message: 'publish minified bundle'
          add: "."
          force: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
